name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Build
      run: make

    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v4.6.2
      with:
        path:  "./mouse_locker"
